# Generated by Django 3.1.7 on 2021-05-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shared_DB_Schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
