# Generated by Django 3.1.7 on 2021-05-18 04:58

import Shared_DB_Schema.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shared_DB_Schema', '0002_auto_20210518_0602'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Shared_DB_Schema.models.ManagerCustom()),
            ],
        ),
    ]
