# Generated by Django 3.1.6 on 2021-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='describe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
