# Generated by Django 3.1.6 on 2021-03-08 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('create', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 8, 14, 13, 34, 657858))),
            ],
        ),
    ]
