# Generated by Django 3.1.6 on 2021-03-12 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('image', models.ImageField(default='123', upload_to='user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(max_length=100)),
                ('postContent', models.TextField()),
                ('postCreate', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 12, 15, 48, 3, 313945))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(default=1)),
                ('content', models.CharField(max_length=250)),
                ('create', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 12, 15, 48, 3, 313945))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
