# Generated by Django 3.1.6 on 2021-03-08 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCreate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 8, 13, 47, 58, 825166)),
        ),
    ]
