# Generated by Django 3.1.6 on 2021-03-08 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210308_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCreate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 8, 14, 48, 30, 315141)),
        ),
    ]
