# Generated by Django 3.1.6 on 2021-03-11 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210310_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCreate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 11, 17, 21, 38, 131336)),
        ),
    ]
